format_version: 4
pipelines:
  "data-sandbox-notebooks":
    group: gp2gp-data-sandbox-infra
    label_template: "${data_sandbox_notebooks[:8]}"
    materials:
      data_sandbox_notebooks:
        plugin_configuration:
          id: git-path
        options:
          url: https://github.com/nhsconnect/prm-gp2gp-data-sandbox-infra.git
          path: stacks/notebooks
          branch: main
    stages:
      - validate:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-validate notebooks dev
      - plan_dev:
          clean_workspace: true
          jobs:
            plan:
              resources:
                - docker
              artifacts:
                - build:
                    source: stacks/notebooks/terraform/dev.tfplan
                    destination: stacks/notebooks/terraform
                - build:
                    source: stacks/notebooks/terraform/.terraform.lock.hcl
                    destination: stacks/notebooks/terraform
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-plan notebooks dev
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ls -lsa
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ls -lsa stacks/notebooks/terraform
      - apply_dev:
          clean_workspace: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: plan_dev
                    job: plan
                    source: stacks/notebooks/terraform/dev.tfplan
                    is_file: yes
                - fetch:
                    stage: plan_dev
                    job: plan
                    source: stacks/notebooks/terraform/.terraform.lock.hcl
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-apply notebooks dev
      - plan_prod:
          clean_workspace: true
          jobs:
            plan:
              resources:
                - docker
              artifacts:
                - build:
                    source: stacks/notebooks/terraform/prod.tfplan
                    destination: stacks/notebooks
                - build:
                    source: stacks/notebooks/terraform/.terraform.lock.hcl
                    destination: stacks/notebooks
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-plan notebooks prod
      - apply_prod:
          clean_workspace: true
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: plan_prod
                    job: plan
                    source: stacks/notebooks/terraform/prod.tfplan
                    is_file: yes
                - fetch:
                    stage: plan_prod
                    job: plan
                    source: stacks/notebooks/terraform/.terraform.lock.hcl
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-apply notebooks prod
