format_version: 4
pipelines:
  "data-sandbox-infra-common-account":
    group: gp2gp-data-sandbox-infra
    label_template: "${data_sandbox[:8]}"
    materials:
      data_sandbox:
        plugin_configuration:
          id: git-path
        options:
          url: https://github.com/nhsconnect/prm-gp2gp-data-sandbox-infra.git
          path: stacks/data-sandbox
          branch: main
    stages:
      - validate:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-validate data-sandbox common_dev
      - plan_common_dev:
          clean_workspace: true
          jobs:
            plan:
              resources:
                - docker
              artifacts:
                - build:
                    source: common_dev.tfplan
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-plan data-sandbox common_dev
      - apply_common_dev:
          clean_workspace: true
          jobs:
            apply:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: plan_common_dev
                    job: plan
                    source: common_dev.tfplan
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-apply data-sandbox common_dev
